import { SIGNIN_ROUTE } from "@/consts/routes";
import { redirect } from "@/i18n/routing";
import { auth } from "@/lib/auth";
import { SidebarInset, SidebarProvider } from "@/components/shadcn/ui/sidebar";
import { Metadata } from "next";
import { headers } from "next/headers";
import React from "react";
import { AppSidebar, PageHeader } from "@/features/layout";
import { SiteHeader } from "@/features/layout";
import { UserRole } from "@prisma/client";
import { Separator } from "@/components/shadcn/ui/separator";

export const metadata: Metadata = {
	title: "Profile",
	description: "Generated by create next app",
};

const NewEventLayout = async ({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { locale: string };
}) => {
	const { locale } = await params;
	const session = await auth.api.getSession({ headers: await headers() });

	if (!session) {
		redirect({ href: SIGNIN_ROUTE, locale });
		return null;
	}

	return (
		<div className="flex flex-col gap-5">
			<PageHeader />
			<Separator />
			{children}
		</div>
	);
};

export default NewEventLayout;
