import { SIGNIN_ROUTE } from "@/config/routes";
import { redirect } from "@/i18n/routing";
import { auth } from "@/lib/auth";
import { Metadata } from "next";
import { headers } from "next/headers";
import React from "react";

export const metadata: Metadata = {
	title: "Profile",
	description: "Generated by create next app",
};

const NewEventLayout = async ({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { locale: string };
}) => {
	const { locale } = await params;
	const session = await auth.api.getSession({ headers: await headers() });

	if (!session) {
		redirect({ href: SIGNIN_ROUTE, locale });
		return null;
	}

	return (
		<div className="new-event-layout flex w-full flex-col gap-6">
			<div
				style={{
					position: "absolute",
					top: -1,
					right: 0,
					bottom: 0,
					left: -1,
					zIndex: 0,
					backgroundImage: `
        linear-gradient(to right, #e2e8f0 1px, transparent 1px),
        linear-gradient(to bottom, #e2e8f0 1px, transparent 1px)
      `,
					backgroundSize: "100px 100px",
					WebkitMaskImage:
						"linear-gradient(to right, #000 0%, transparent 30%, transparent 70%, #000 100%)",
					maskImage:
						"linear-gradient(to right, #000 0%, transparent 30%, transparent 70%, #000 100%)",
				}}
			/>
			{children}
		</div>
	);
};

export default NewEventLayout;
