import { SIGNIN_ROUTE } from "@/helpers/routes";
import { redirect } from "@/i18n/routing";
import { auth } from "@/lib/auth";
import { UserType } from "@/types/user";
import { UserRole } from "@prisma/client";
import { Metadata } from "next";
import { headers } from "next/headers";
import OrganizerEventsPage from "./components/organizer-events";

export const metadata: Metadata = {
	title: "Profile",
	description: "Generated by create next app",
};

export default async function EventsPage({
	params,
}: {
	params: Promise<{ locale: string }>;
}) {
	// Ждем получения параметров (в Next.js 15 это Promise)
	const { locale } = await params;
	const session = await auth.api.getSession({ headers: await headers() });

	if (!session) {
		redirect({ href: SIGNIN_ROUTE, locale });
		return null;
	}

	const role = session.user.role ?? UserRole.USER;

	console.log(role);

	const dashboards = {
		[UserRole.ADMIN]: <div>admin dashboard</div>,
		[UserRole.ORGANIZER]: <OrganizerEventsPage />,
		[UserRole.USER]: <div>participant dashboard</div>,
	};

	return dashboards[role] ?? <OrganizerEventsPage />;
}
