import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	generator: 'v0.app'
};

export default function RootLayout({
																		 children,
																	 }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main>
			<section>1</section>
			<aside>{children}</aside>
			</main>
	);
}
