import { SIGNIN_ROUTE } from "@/helpers/routes";
import { redirect } from "@/i18n/routing";
import { auth } from "@/lib/auth";
import {
	SidebarInset,
	SidebarProvider,
	SidebarTrigger,
} from "@/shadcn/ui/sidebar";
import { Metadata } from "next";
import { headers } from "next/headers";
import React from "react";
import { SidebarLeft } from "#/components/sidebar-left";
import { Separator } from "@/shadcn/ui/separator";
import {
	Breadcrumb,
	BreadcrumbItem,
	BreadcrumbLink,
	BreadcrumbList,
	BreadcrumbPage,
	BreadcrumbSeparator,
} from "@/shadcn/ui/breadcrumb";
import { SidebarRight } from "#/components/sidebar-right";
import { UserRole } from "@prisma/client";
import { useUser } from "@/hooks/use-user";
import Breadcrumbs from "../components/breadcrumbs";

export const metadata: Metadata = {
	title: "Profile",
	description: "Generated by create next app",
};

const ProfileLayout = async ({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) => {
	// Ждем получения параметров (в Next.js 15 это Promise)
	const { locale } = await params;
	const session = await auth.api.getSession({ headers: await headers() });

	if (!session) {
		redirect({ href: SIGNIN_ROUTE, locale });
		return null;
	}

	return (
		<SidebarProvider>
			<SidebarLeft
				user={{
					...session.user,
					role: session.user.role ?? UserRole.USER,
				}}
			/>
			<SidebarInset>
				<header className="flex h-14 shrink-0 items-center gap-2 border-b px-4">
					<SidebarTrigger className="-ml-1" />
					<Separator
						orientation="vertical"
						className="mr-2 data-[orientation=vertical]:h-14"
					/>
					<Breadcrumbs />
					{/* <Breadcrumb>
						<BreadcrumbList>
							<BreadcrumbItem className="hidden md:block">
								<BreadcrumbLink href="#">
									Build Your Application
								</BreadcrumbLink>
							</BreadcrumbItem>
							<BreadcrumbSeparator className="hidden md:block" />
							<BreadcrumbItem>
								<BreadcrumbPage>Data Fetching</BreadcrumbPage>
							</BreadcrumbItem>
						</BreadcrumbList>
					</Breadcrumb> */}
				</header>
				<main className="flex flex-1 flex-col gap-4 p-6">
					{children}
					{/* <div className="bg-muted/50 mx-auto h-24 w-full max-w-3xl rounded-xl" />
					<div className="bg-muted/50 mx-auto h-screen w-full max-w-3xl rounded-xl" /> */}
				</main>
			</SidebarInset>
			<SidebarRight
				user={{
					...session.user,
					role: session.user.role ?? UserRole.USER,
				}}
			/>
		</SidebarProvider>
	);
};

export default ProfileLayout;
