import { SIGNIN_ROUTE } from "@/consts/routes";
import { redirect } from "@/i18n/routing";
import { auth } from "@/lib/auth";
import { SidebarInset, SidebarProvider } from "@/components/shadcn/ui/sidebar";
import { Metadata } from "next";
import { headers } from "next/headers";
import React from "react";
import { AppSidebar } from "@/features/layout";
import { SiteHeader } from "@/features/layout";
import { UserRole } from "@prisma/client";
import { MobileMenu } from "@/components/layout/menu";

export const metadata: Metadata = {
	title: "Profile",
	description: "Generated by create next app",
};

const ProfileLayout = async ({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { locale: string };
}) => {
	const { locale } = await params;
	const session = await auth.api
		.getSession({ headers: await headers() })
		.catch((e) => {
			console.error("getSession error:", e);
			return null;
		});

	console.log("session:", JSON.stringify(session?.user?.id));

	if (!session?.user) {
		redirect({ href: SIGNIN_ROUTE, locale });
		return null;
	}

	return (
		<div className="[--header-height:calc(--spacing(14))]">
			<SidebarProvider className="flex flex-col">
				<SiteHeader />
				<div className="flex flex-1">
					<AppSidebar
						user={{
							...session.user,
							role: session.user.role ?? UserRole.USER,
						}}
					/>
					<SidebarInset className="h-full">
						<main className="profile-layout flex flex-1 flex-col gap-4 p-4 px-5">
							{children}
						</main>
					</SidebarInset>
				</div>
			</SidebarProvider>

			<MobileMenu />
		</div>
	);
};

export default ProfileLayout;
