export enum TypeMail {
	AUTH = 1,
	INVITATION = 2,
	CODE = 3,
}

export enum CodeError {
	DEFAULT = 0,
	VALIDATION_ERROR = 1,
	USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL = 2,
	INVALID_EMAIL = 3,
	PASSWORD_TOO_SHORT = 4,
	INVALID_TOKEN = 5,
	TOKEN_EXPIRED = 6,
	EMAIL_NOT_FOUND = 7,
}
