import type { Metadata } from "next";
import "@/app/globals.css";
import "@/app/base.scss";
import { SIGNIN_ROUTE } from "@/helpers/routes";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { redirect } from "@/i18n/routing";

export const metadata: Metadata = {
	title: "Admin panel",
	description: "Generated by create next app",
};

export default async function AdminLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	const session = await auth.api.getSession({
		headers: await headers(),
	});

	if (!session) {
		redirect({ href: SIGNIN_ROUTE, locale });
		return null;
	}

	return (
		<div className="p-6">
			{session?.user.role !== "ADMIN" ? (
				<p className="text-red-600">Access denied!</p>
			) : (
				<div className="flex flex-col gap-5">
					<header>
						<h1 className="text-4xl">Admin Dashboard</h1>
						<h2 className="text-xl font-medium">
							Hello, {session.user.email}
						</h2>
					</header>

					<section>{children}</section>
				</div>
			)}
		</div>
	);
}
