import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Poppins } from "next/font/google";
import { Toaster } from "@/shadcn/ui/sonner";
import "../globals.css";
import "@/app/base.scss";

const fontPoppins = Poppins({
	subsets: ["latin"],
	variable: "--font-sans",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "StworzEvent.pl - DEV",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	// Получаем сообщения для текущего языка
	const messages = await getMessages();
	return (
		<html
			lang={locale}
			className={`${fontPoppins.variable} h-screen bg-background`}
		>
			<body className="antialiased h-full">
				<NextIntlClientProvider messages={messages}>
					<Toaster />
					{children}
				</NextIntlClientProvider>
				<SpeedInsights />
				<Analytics />
			</body>
		</html>
	);
}
