import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Poppins } from "next/font/google";
import "../globals.css";
import "@/app/base.scss";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "@/components/shadcn/ui/sonner";

const fontPoppins = Poppins({
	subsets: ["latin"],
	variable: "--font-sans",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "StworzEvent.pl - DEV",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	// Получаем сообщения для текущего языка
	const messages = await getMessages();
	return (
		<html lang={locale} className={`${fontPoppins.variable}`}>
			<body className="antialiased min-h-screen flex flex-col">
				<QueryProvider>
					<NextIntlClientProvider messages={messages}>
						<Toaster />
						{children}
					</NextIntlClientProvider>
				</QueryProvider>
				<SpeedInsights />
				<Analytics />
			</body>
		</html>
	);
}
