import type { Metadata } from "next";
import ReturnBtn from "../components/return-btn";
import { HOME_ROUTE } from "@/helpers/routes";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	generator: "v0.app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className="h-full flex bg">
			<section className="w-2/3 h-full flex justify-center items-center bg-accent">
				1
			</section>
			<aside className="w-1/3 min-w-[500px] h-full flex flex-col justify-center items-center p-6 ">
				{children}

				<ReturnBtn href={HOME_ROUTE} label="back" />
			</aside>
		</main>
	);
}
