import type { Metadata } from "next";
import ReturnBtn from "../components/return-btn";
import { HOME_ROUTE } from "@/helpers/routes";
import Image from "next/image";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	generator: "v0.app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main
			className="h-full flex bg"
			style={{
				backgroundImage: "url(/images/bg/sign-in-bg.png)",
				backgroundRepeat: "no-repeat",
				backgroundSize: "cover",
				backgroundPosition: "center",
			}}
		>
			<section className="w-2/3 h-full flex p-10 justify-center items-center">
				<Image
					src="/logos/logo_white.svg"
					alt="logo_white"
					width={457}
					height={103}
				/>
			</section>
			<aside className="w-1/3 min-w-[450px] h-full flex flex-col gap-9 justify-center items-center p-6 bg-background">
				{children}
			</aside>
		</main>
	);
}
